### ISSUE TITLE
Link to / promote / encourage translations

### ISSUE THREAD

**Issue by onyxfish** [Quartz/bad-data-guide#26]
http://cn.gijn.org/2016/01/10/quartz%E5%9D%8F%E6%95%B0%E6%8D%AE%E6%8C%87%E5%8D%97%E7%B2%BE%E9%80%89%EF%BC%9A%E5%A4%84%E7%90%86%E6%95%B0%E6%8D%AE%E7%9A%84%E6%AD%A3%E7%A1%AE%E6%96%B9%E5%BC%8F%E4%B8%80%E8%A7%88/

**Comment by nsonnad** [comment]
Pinging @clkao as he may know someone interested in doing a full Chinese translation

**Comment by miguelpaz** [comment]
@onyxfish this guide is super useful, thanks for it. I may have time in the summer to translate to Spanish.

**Comment by onyxfish** [comment]
Added Translations section up top with links to Chinese and Spanish versions
