### ISSUE TITLE
Data should be chronologically increasing (or decreasing)

### ISSUE THREAD

**Issue by tjchambers** [Quartz/bad-data-guide#35]
I have seen multiple situations where data is logged chronologically or time. A current example is song play counts, or YouTube views. If the data is logged day after day these numbers should stay the same or more likely INCREASE. So when you see them... 
- decrease
- go to zero after being positive
- GO WAY up then return to a more normal linearly increasing value

The data is suspect.

Sometimes the data can be "repaired" by removing the wild swings. But that is not always simple depending on the bandwdith of "normal" data.

**Comment by onyxfish** [comment]
Hi Tim, this isn't a problem I've come across before. Can you explain a little bit more about why you think this situation arises? Is this a case where there were unique identifiers that got sorted out of order, or something else?

**Comment by tjchambers** [comment]
It happens when the data supplier has a bug, or when the keys for looking up data - for example using an api - are incorrect, and then corrected. Lots of potential for error, but the bottomline it is somewhat "obvious" bad data from an expectation viewpoint.

**Comment by SusanDMcLeod** [comment]
Why am I getting all these emails all of a sudden?



*Sue Conroy McLeod*
President
telephone (630) 920-7800 X211
facsimile (630) 323-5700
mobile (630) 918-6413
email sue@conroymedialtd.com
@SusanMcLeod

**Comment by onyxfish** [comment]
@tjchambers That's interesting, but my gut says it not quite a clear enough case to tell people to watch out for it. (Veers a bit too close to simply saying "The data is wrong".)  I'll keep it in mind for the future if I get other suggestions along the same lines.

@SusanDMcLeod I'm not sure, but you must have subscribed to issues for the Quartz Guide to Bad Data—either on this particular issue, or for the project as a whole.

**Comment by SusanDMcLeod** [comment]
How do I unsubscribe? Sorry - I am not a programmer and don't know how I
started getting these emails.  They just started about an hour ago.  Thanks
in advance.




*Sue Conroy McLeod*
President
telephone (630) 920-7800 X211
facsimile (630) 323-5700
mobile (630) 918-6413
email sue@conroymedialtd.com
@SusanMcLeod

**Comment by onyxfish** [comment]
@SusanDMcLeod My best guess is that you need to here:

https://github.com/Quartz/bad-data-guide

And click "Unwatch" at the top of the page. If that doesn't work you can change all your notification settings on this page:

https://github.com/settings/notifications
